- name: Install homebrew
  command: '{{ dotfiles_dir }}/brew/install.sh'
  register: command_output
  changed_when: "'Brew is installed' not in command_output.stdout"
- name: Ensure homebrew is updated
  community.general.homebrew:
    update_homebrew: true
- name: Install with homebrew cask
  community.general.homebrew_cask:
    name: "{{ brew_casks }}"
    state: present
  ignore_errors: yes