- name: Install homebrew
  command: '{{ dotfiles_dir }}/brew/install.sh'
  register: command_output
  changed_when: "'installed' not in command_output.stdout"
- name: Ensure homebrew is updated
  homebrew:
    state: latest
    update_homebrew: yes
- name: Install with homebrew cask
  homebrew:
    name: "{{ brew_casks }}"
    state: present
  ignore_errors: yes