- hosts: localhost 
  vars:
    home_dir: "{{ ansible_env.HOME }}" 
    dotfiles_dir: "{{ playbook_dir }}/.."
    modules_dir: '/etc/ansible/modules'
    common:
      - bash-completion
      - docker
      - git
      - python
      - pyenv
      - tree
      - watch
      - wget
      - zsh
      - zsh-completions
  tasks:
  - name: Create ansible directory
    file: path={{ modules_dir }} state=directory
    #become: true
  - name: Symlink ansible hosts
    file:
      src: '{{ playbook_dir }}/hosts'
      dest: '/etc/ansible/hosts' 
      state: link
      force: yes
    #become: true
  - include_tasks: "tasks/os-specific.yml"
  - include_vars: "{{ os_vars }}"
    when: vars_exist
  - include_tasks: "tasks/setup-zsh.yml"
  - name: Symlink config files
    file:
      src: '{{ item.src }}'
      dest: '{{ home_dir }}/{{ item.path }}'
      state: link
      force: yes
    with_filetree: '{{ dotfiles_dir }}/home/'
    when: item.state == 'file'
  - include_tasks: "{{ os_tasks }}"
    when: tasks_exist
  - name: Install with {{ ansible_pkg_mgr }}
    action: >
      {{ ansible_pkg_mgr }} name="{{ utils }}" state=latest
    become: "{{ false if ansible_pkg_mgr == 'homebrew' else true }}"
