- hosts: localhost
  tasks:
    - debug: msg="{{ ansible_facts['distribution'] }}.yml"
    - debug: msg="{{ ansible_facts['distribution_release'] }}"
    - debug: msg="{{ ansible_facts['distribution_version'] }}"
    - debug: msg="{{ ansible_facts['pkg_mgr'] }}"
    - name: Stat OS-specific vars and tasks
      stat:
        path: "{{ item }}"
      with_items:
        - "vars/{{ ansible_facts['distribution'] }}.yml"
        - "tasks/{{ ansible_facts['distribution'] }}.yml"
        - "vars/some.yml"
      register: os
    - set_fact:
        path_stat: "{{ path_stat | default([]) + [ {item.item: item.stat.exists} ] }}"
      with_items: "{{ os.results }}"
    - debug: msg="{{ path_stat }}"
    - debug: msg="{{ ansible_facts['os_family'] }}"